-- CommandLayer.spoon/tests/generated.lua
-- docs/api.md and the JSON Schemas in config/ are generated by
-- tests/reference.lua: each is what it would write, and leaves nothing out.

local T = ...
local check, group = T.check, T.group

local R = assert(loadfile(T.dir .. "tests/reference.lua"))(T)
local REGENERATE = "run `lua tests/reference.lua` in the Spoon's folder"

-- Generated before adopting: the harness's recording presenter is no presenter that ships.
local kernel = R.kernel()
local generated = R.generate(kernel)
local other = R.kernel()
local again = R.generate(other)
local cl = T.adopt(kernel)

local function nonEmpty(text) return type(text) == "string" and text:match("%S") ~= nil end

group("generated files")

check("the reference and the JSON Schemas are current", (function()
        local stale = {}
        for _, path in ipairs(R.FILES) do
          if T.readSource(path) ~= generated[path] then stale[#stale + 1] = path end
        end
        return #stale == 0, table.concat(stale, ", ") .. " out of date: " .. REGENERATE
      end)())

check("two kernels generate the same bytes", (function()
        local differ = {}
        for _, path in ipairs(R.FILES) do
          if again[path] ~= generated[path] then differ[#differ + 1] = path end
        end
        return #differ == 0, table.concat(differ, ", ")
      end)())

check("a description changed in the schema changes what is generated", (function()
        other.schemas.view.fields.name.description = "Changed"
        local changed = R.generate(other)
        return changed["docs/api.md"] ~= generated["docs/api.md"]
               and changed["config/settings.schema.json"] ~= generated["config/settings.schema.json"]
      end)())

check("the settings schema is JSON, and names every setting there is", (function()
        local schema = cl.decodeJSONC(generated["config/settings.schema.json"])
        local properties = type(schema) == "table" and schema.properties
        if type(properties) ~= "table" then return false, "does not decode" end
        local missing = {}
        local defaults = cl.decodeJSONC(cl.readText(cl.SPOON_DIR .. "config/defaults.jsonc"))
        for key in pairs(defaults) do
          if properties[key] == nil then missing[#missing + 1] = key end
        end
        if properties["$schema"] == nil then missing[#missing + 1] = "$schema" end
        for _, owner in ipairs(cl.settingOwners()) do
          if owner.kind == "extension" and properties[owner.name .. ".enabled"] == nil then
            missing[#missing + 1] = owner.name .. ".enabled"
          end
          for key in pairs(type(owner.settings) == "table" and owner.settings or {}) do
            if properties[owner.name .. "." .. key] == nil then missing[#missing + 1] = owner.name .. "." .. key end
          end
        end
        return #missing == 0, table.concat(missing, ", ")
      end)())

check("the keybindings schema is JSON, and offers every command there is", (function()
        local schema = cl.decodeJSONC(generated["config/keybindings.schema.json"])
        local ok, offered = pcall(function() return schema.items.properties.command.anyOf[1].enum end)
        if not ok or type(offered) ~= "table" then return false, "no command enum" end
        local set, missing = {}, {}
        for _, id in ipairs(offered) do set[id] = true end
        for _, command in ipairs(cl.getCommands()) do
          if not set[command.id] then missing[#missing + 1] = command.id end
        end
        return #cl.getCommands() > 0 and #missing == 0, table.concat(missing, ", ")
      end)())

check("every kind of spec, each of its fields, and each keybinding field is described", (function()
        local bare = {}
        for kind, schema in pairs(cl.schemas) do
          if not nonEmpty(schema.description) then bare[#bare + 1] = kind end
          for name, field in pairs(schema.fields) do
            if not nonEmpty(field.description) then bare[#bare + 1] = kind .. "." .. name end
          end
        end
        for name, description in pairs(cl.keybindingFields) do
          if not nonEmpty(description) then bare[#bare + 1] = "keybinding." .. name end
        end
        return #bare == 0, table.concat(bare, ", ")
      end)())

check("every list an extension reads, and each of its fields, is described", (function()
        local bare = {}
        for name, shape in pairs(cl.listShapes) do
          if not nonEmpty(shape.description) then bare[#bare + 1] = name end
          for field, doc in pairs(shape.fields) do
            if not nonEmpty(doc.description) then bare[#bare + 1] = name .. "." .. field end
          end
        end
        return next(cl.listShapes) ~= nil and #bare == 0, table.concat(bare, ", ")
      end)())

check("every member of every plugin API is described, and every description names a member", (function()
        local bare, members = {}, {}
        for kind, list in pairs(cl.apiMembers()) do
          for _, member in ipairs(list) do
            members[member.name] = true
            if not nonEmpty(member.description) then bare[#bare + 1] = kind .. ": cl." .. member.name end
          end
        end
        for name in pairs(cl.apiDescriptions) do
          if not members[name] then bare[#bare + 1] = "no member " .. name end
        end
        return #bare == 0, table.concat(bare, ", ")
      end)())

check("the kernel's settings are described: every key defaults.jsonc has, no other, of its type", (function()
        local defaults = {}
        -- "maccy.enabled" is an extension's setting, described with the extension.
        for key, value in pairs(cl.decodeJSONC(cl.readText(cl.SPOON_DIR .. "config/defaults.jsonc"))) do
          if not key:find(".", 1, true) then defaults[key] = value end
        end
        local wrong = {}
        local function compare(label, docs, values)
          for key, value in pairs(values) do
            local doc = docs[key]
            if type(doc) ~= "table" or not nonEmpty(doc.description) then
              wrong[#wrong + 1] = label .. key .. " is not described"
            elseif not (type(value) == "table" and next(value) == nil) and cl.jsonType(value) ~= doc.type
                   and not (doc.type == "number" and type(value) == "number") then
              wrong[#wrong + 1] = label .. key .. " is " .. cl.jsonType(value) .. ", described as " .. tostring(doc.type)
            end
            if type(doc) == "table" and doc.properties and type(value) == "table" then
              compare(label .. key .. ".", doc.properties, value)
            end
          end
          for key in pairs(docs) do
            if values[key] == nil then wrong[#wrong + 1] = label .. key .. " is not in defaults.jsonc" end
          end
        end
        compare("", cl.kernelSettings, defaults)
        return #wrong == 0, table.concat(wrong, "; ")
      end)())
