-- CommandLayer.spoon/tests/reference.lua
-- Writes docs/api.md, config/settings.schema.json and
-- config/keybindings.schema.json from the schema, the plugin API and the
-- plugins that ship. Run with:  lua tests/reference.lua   (from the Spoon's
-- folder). Not a suite: tests/generated.lua loads it to check the files on
-- disk are what it would write.

local given = ...
local T = type(given) == "table" and given or nil
if not T then
  local dir = arg and arg[0] and arg[0]:match("^(.-)tests/[^/]*$") or ""
  T = assert(loadfile((dir == "" and "./" or dir) .. "tests/harness.lua"))(dir == "" and "./" or dir)
end

local R = {}

R.FILES = { "config/keybindings.schema.json", "config/settings.schema.json", "docs/api.md" }

local DRAFT = "http://json-schema.org/draft-07/schema#"
local COMMENT = "Generated by `lua tests/reference.lua`; do not edit."

-- The shipped files alone: a person's own folder would change what is written.
-- Every extension on, so a command of one shipped switched off is still one a
-- keybinding may name.
function R.kernel()
  return T.setup(T.loadKernel(), T.everyExtensionOn)
end

----------------------------------------------------------------------
-- HELPERS
----------------------------------------------------------------------

local function sortedKeys(t)
  local keys = {}
  for key in pairs(t) do keys[#keys + 1] = key end
  table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
  return keys
end

-- encodeJSON writes an empty list as {}, so an empty table is left out.
local function isEmpty(value)
  return type(value) == "table" and next(value) == nil
end

local function luaTypes(field)
  return type(field.type) == "table" and field.type or { field.type }
end

local function presenterNames(K) return sortedKeys(K.presenters) end

local function matcherNames(K)
  local names = {}
  for _, matcher in ipairs(K.loadedMatchers or K.matchers) do names[#names + 1] = matcher.name end
  table.sort(names)
  return names
end

local JSON_OF_LUA = { string = "string", when = "string", number = "number", boolean = "boolean" }

----------------------------------------------------------------------
-- settings.schema.json
----------------------------------------------------------------------

local kindSchema

-- A spec field as a settings file writes it; nil for one only code can hold.
local function fieldSchema(K, field)
  local out, types = { description = field.description }, {}
  for _, luaType in ipairs(luaTypes(field)) do
    if JSON_OF_LUA[luaType] then
      types[#types + 1] = JSON_OF_LUA[luaType]
    elseif luaType == "table" and field.list then
      types[#types + 1], out.items = "array", kindSchema(K, field.list)
    elseif luaType == "table" and field.items then
      types[#types + 1], out.items = "array", { type = JSON_OF_LUA[field.items] }
    elseif luaType == "table" and field.map then
      types[#types + 1], out.additionalProperties = "object", kindSchema(K, field.map)
    elseif luaType == "table" then
      types[#types + 1] = "array"
      types[#types + 1] = "object"
    end
  end
  -- Only a function: nothing a file can hold.
  if #types == 0 and luaTypes(field)[1] ~= "any" then return nil end
  if #types == 1 then out.type = types[1] elseif #types > 1 then out.type = types end
  if field.enum then out.enum = field.enum end
  if field.presenter then out.enum = presenterNames(K) end
  return out
end

function kindSchema(K, kind, extra)
  local schema = K.schemas[kind]
  local properties, required = {}, {}
  for name, field in pairs(schema.fields) do
    if field.inFiles ~= false then
      properties[name] = fieldSchema(K, field)
      if field.required and properties[name] then required[#required + 1] = name end
    end
  end
  for name, field in pairs(extra or {}) do properties[name] = fieldSchema(K, field) end
  table.sort(required)
  local out = { type = "object", description = schema.description, properties = properties,
                additionalProperties = false }
  if #required > 0 then out.required = required end
  return out
end

local DECLARATION_KEYS = { "type", "default", "description", "markdownDescription", "enum", "enumDescriptions",
                           "minimum", "maximum", "deprecationMessage", "order" }

-- VS Code's own keys for a setting, pattern left out: ours is a Lua pattern,
-- which a JSON Schema would read as a regular expression.
local function declarationSchema(decl)
  local out = {}
  for _, key in ipairs(DECLARATION_KEYS) do
    if decl[key] ~= nil and not isEmpty(decl[key]) then out[key] = decl[key] end
  end
  return out
end

local function settingOwners(K)
  local owners = K.settingOwners()
  table.sort(owners, function(a, b)
    if a.displayName:lower() ~= b.displayName:lower() then return a.displayName:lower() < b.displayName:lower() end
    return a.name < b.name
  end)
  return owners
end

local function shippedDefaults(K)
  return K.decodeJSONC(K.readText(K.SPOON_DIR .. "config/defaults.jsonc")) or {}
end

local MENUS_DESCRIPTION = "Which pickers its rows and commands are in, over what it declares: a menu's "
  .. "name to true (added) or false (taken out); a menu not named keeps the declaration. "
  .. "A command that is no row anywhere stays none."

local function enabledDescription(owner)
  return ("Whether %s is on; a change applies on reload.%s"):format(owner.displayName,
    owner.description and (" " .. owner.description .. ".") or "")
end

function R.settingsSchema(K)
  local defaults, properties = shippedDefaults(K), {}
  properties["$schema"] = { type = "string",
                            description = "Where an editor finds this file: the Spoon's config/settings.schema.json." }

  for key, doc in pairs(K.kernelSettings) do
    local p = { type = doc.type, description = doc.description }
    local default = defaults[key]
    if default ~= nil and not isEmpty(default) and key ~= "views" then p.default = default end
    for sub, subdoc in pairs(doc.properties or {}) do
      p.properties = p.properties or {}
      local sp = { type = subdoc.type, description = subdoc.description }
      local subDefault = type(default) == "table" and default[sub] or nil
      if subDefault ~= nil and not isEmpty(subDefault) then sp.default = subDefault end
      if subdoc.type == "object" then sp.additionalProperties = { type = "string" } end
      p.properties[sub] = sp
    end
    if doc.properties then p.additionalProperties = false end
    properties[key] = p
  end

  properties.views.items = kindSchema(K, "view", K.kernelSettings.views.fields)
  properties.matchers.items = { type = "string", enum = matcherNames(K) }
  properties.rankers.properties, properties.rankers.additionalProperties = {}, false
  for _, ranker in ipairs(K.rankers) do
    properties.rankers.properties[ranker.name] = { type = "number", description = ranker.description }
  end
  properties.prefixes.additionalProperties = { type = { "string", "array" }, items = { type = "string" } }
  properties.aliases.additionalProperties = { type = { "string", "array" }, items = { type = "string" } }
  properties.presenter.enum = presenterNames(K)
  properties.logLevel.enum = K.logLevels

  local names = {}
  for _, owner in ipairs(settingOwners(K)) do
    names[#names + 1] = owner.name
    if owner.kind == "extension" then
      properties[owner.name .. ".enabled"] = { type = "boolean", default = defaults[owner.name .. ".enabled"] ~= false,
                                               description = enabledDescription(owner) }
      properties[owner.name .. ".menus"] = { type = "object", additionalProperties = { type = "boolean" },
                                             description = MENUS_DESCRIPTION }
    end
    for key, decl in pairs(type(owner.settings) == "table" and owner.settings or {}) do
      if type(decl) == "table" then properties[owner.name .. "." .. key] = declarationSchema(decl) end
    end
  end
  table.sort(names)

  return {
    ["$schema"] = DRAFT, ["$comment"] = COMMENT,
    title = "Command Layer settings",
    description = "settings.json, over the Spoon's config/defaults.jsonc.",
    type = "object",
    properties = properties,
    -- A dotted key naming nothing that ships is a person's own extension's.
    patternProperties = {
      ["^(?!(?:" .. table.concat(names, "|") .. ")\\.)[A-Za-z0-9_-]+\\."] = {
        description = "A setting of an extension, presenter or ranker that does not ship with the Spoon.",
      },
    },
    additionalProperties = false,
  }
end

----------------------------------------------------------------------
-- keybindings.schema.json
----------------------------------------------------------------------

local function commandIds(K)
  local ids = {}
  for _, command in ipairs(K.getCommands()) do ids[#ids + 1] = command.id end
  table.sort(ids)
  return ids
end

function R.keybindingsSchema(K)
  local fields = K.keybindingFields
  return {
    ["$schema"] = DRAFT, ["$comment"] = COMMENT,
    title = "Command Layer keybindings",
    description = "keybindings.json: entries after the Spoon's config/defaultKeybindings.jsonc.",
    type = "array",
    items = {
      type = "object",
      properties = {
        key = { type = "string", description = fields.key },
        command = { description = fields.command,
                    anyOf = { { type = "string", enum = commandIds(K) }, { type = "string", pattern = "^-" } } },
        args = { description = fields.args },
        when = { type = "string", description = fields.when },
        global = { type = "boolean", description = fields.global },
        ["repeat"] = { type = "boolean", description = fields["repeat"] },
      },
      required = { "command" },
      additionalProperties = false,
    },
  }
end

----------------------------------------------------------------------
-- docs/api.md
----------------------------------------------------------------------

local function cell(text)
  return (tostring(text or ""):gsub("\n", " "):gsub("|", "\\|"))
end

local function code(text) return "`" .. cell(text) .. "`" end

local function typeName(field)
  local words = {}
  for _, luaType in ipairs(luaTypes(field)) do
    if luaType == "table" and field.list then words[#words + 1] = "list of " .. field.list .. "s"
    elseif luaType == "table" and field.map then words[#words + 1] = "table of " .. field.map .. "s by key"
    elseif luaType == "table" and field.items then words[#words + 1] = "list of " .. field.items .. "s"
    elseif luaType == "when" then words[#words + 1] = "when clause"
    else words[#words + 1] = luaType end
  end
  return table.concat(words, " or ")
end

local function withEnum(description, enum)
  if type(enum) ~= "table" then return description end
  local values = {}
  for i, value in ipairs(enum) do values[i] = code(value) end
  return (description or "") .. " One of " .. table.concat(values, ", ") .. "."
end

local function jsonCell(K, value)
  if value == nil then return "" end
  return code(K.encodeJSON(value, true))
end

function R.reference(K)
  local out = {}
  local function line(text) out[#out + 1] = text or "" end
  local function table_(header)
    line("| " .. table.concat(header, " | ") .. " |")
    line("|" .. ("---|"):rep(#header))
  end
  local function row(cells) line("| " .. table.concat(cells, " | ") .. " |") end

  line("# Command Layer reference")
  line()
  line("Generated by `lua tests/reference.lua` from `core/schema.lua`, `core/api.lua` and the plugins")
  line("that ship. Do not edit it: change those and generate it again. The harness fails while it is out of date.")
  line()
  line("## Specs")
  for _, kind in ipairs(sortedKeys(K.schemas)) do
    local schema = K.schemas[kind]
    line()
    line("### " .. kind)
    line()
    line(schema.description)
    line()
    table_({ "Field", "Type", "Required", "Description" })
    for _, name in ipairs(sortedKeys(schema.fields)) do
      local field = schema.fields[name]
      row({ code(name), cell(typeName(field)), field.required and "yes" or "",
            cell(withEnum(field.description, field.enum)) })
    end
  end

  local defaults = shippedDefaults(K)
  line()
  line("## Lists")
  line()
  line("What an extension reads of the layer's own lists. Each call gives a fresh copy, every entry holding")
  line("these fields and no other; changing one changes nothing the layer holds.")
  for _, name in ipairs(sortedKeys(K.listShapes)) do
    local shape = K.listShapes[name]
    line()
    line("### " .. name)
    line()
    line(shape.description)
    line()
    table_({ "Field", "Type", "Description" })
    for _, field in ipairs(sortedKeys(shape.fields)) do
      row({ code(field), cell(typeName(shape.fields[field])), cell(shape.fields[field].description) })
    end
  end

  line()
  line("## Settings")
  line()
  line("A profile's `settings.json` sets any of these over `config/defaults.jsonc`. An editor completes and")
  line("checks it when it starts with `\"$schema\"` naming the Spoon's `config/settings.schema.json`; VS Code's")
  line("`json.schemas` setting does the same for `keybindings.json` with `config/keybindings.schema.json`.")
  line()
  line("### The kernel's")
  line()
  table_({ "Key", "Type", "Default", "Description" })
  for _, key in ipairs(sortedKeys(K.kernelSettings)) do
    local doc = K.kernelSettings[key]
    row({ code(key), doc.type, key == "views" and "" or jsonCell(K, defaults[key]), cell(doc.description) })
    for _, sub in ipairs(sortedKeys(doc.properties or {})) do
      local subdoc = doc.properties[sub]
      row({ code(key .. "." .. sub), subdoc.type, jsonCell(K, type(defaults[key]) == "table" and defaults[key][sub] or nil),
            cell(subdoc.description) })
    end
  end

  line()
  line("### Declared by extensions, presenters and rankers")
  for _, owner in ipairs(settingOwners(K)) do
    line()
    line(("#### %s (`%s`, %s)"):format(owner.displayName, owner.name, owner.kind))
    if owner.description then
      line()
      line(owner.description)
    end
    line()
    table_({ "Setting", "Type", "Default", "Description" })
    if owner.kind == "extension" then
      row({ code(owner.name .. ".enabled"), "boolean",
            code(tostring(defaults[owner.name .. ".enabled"] ~= false)), cell(enabledDescription(owner)) })
      row({ code(owner.name .. ".menus"), "object", "", cell(MENUS_DESCRIPTION) })
    end
    local settings = type(owner.settings) == "table" and owner.settings or {}
    local keys = sortedKeys(settings)
    table.sort(keys, function(a, b) return K.settingBefore(settings, a, b) end)
    for _, key in ipairs(keys) do
      local decl = settings[key]
      if type(decl) == "table" then
        local about = decl.markdownDescription or decl.description
        if decl.deprecationMessage then about = (about or "") .. " Deprecated: " .. decl.deprecationMessage end
        row({ code(owner.name .. "." .. key), cell(decl.type), jsonCell(K, decl.default),
              cell(withEnum(about, decl.enum)) })
      end
    end
  end

  line()
  line("## Keybindings")
  line()
  line("`keybindings.json` is a list of entries, each after the shipped `config/defaultKeybindings.jsonc`.")
  line()
  table_({ "Field", "Required", "Description" })
  for _, name in ipairs(sortedKeys(K.keybindingFields)) do
    row({ code(name), name == "command" and "yes" or "", cell(K.keybindingFields[name]) })
  end

  line()
  line("## Plugin API")
  line()
  line("What `cl` holds for each kind of plugin. Reading or writing any other name raises.")
  local members = K.apiMembers()
  for _, kind in ipairs(sortedKeys(members)) do
    line()
    line("### " .. kind)
    line()
    table_({ "Member", "Description" })
    for _, member in ipairs(members[kind]) do row({ code(member.name), cell(member.description) }) end
  end

  line()
  line("## Commands")
  line()
  line("Every command the shipped extensions and the kernel register, by id.")
  line()
  table_({ "Command", "Title", "Extension" })
  local commands = K.getCommands()
  table.sort(commands, function(a, b) return a.id < b.id end)
  for _, command in ipairs(commands) do
    local title = command.category and (command.category .. ": " .. command.title) or command.title
    row({ code(command.id), cell(title), command.extension and code(command.extension) or "kernel" })
  end

  return table.concat(out, "\n") .. "\n"
end

----------------------------------------------------------------------

function R.generate(K)
  return {
    ["config/settings.schema.json"] = K.encodeJSON(R.settingsSchema(K)) .. "\n",
    ["config/keybindings.schema.json"] = K.encodeJSON(R.keybindingsSchema(K)) .. "\n",
    ["docs/api.md"] = R.reference(K),
  }
end

if given == T then return R end

local K = R.kernel()
local files = R.generate(K)
os.execute(("mkdir -p %q"):format(T.dir .. "docs"))
for _, path in ipairs(R.FILES) do
  local handle = assert(io.open(T.dir .. path, "w"))
  handle:write(files[path])
  handle:close()
  print("wrote " .. path)
end
