-- Which app is in front, what is on the clipboard, this Mac's name and
-- whether it is online.
--
-- They are captures like any other, so a launcher built around
-- something else -- the focused window, the current Space, the playing
-- track -- replaces this file rather than editing the kernel. Nearly
-- every other extension reads ctx.frontmostApp, which is a reason to
-- run first and not a reason to be privileged.

local M = {}

local layer

-- SCNetworkReachability's reading of a route to the internet: reachable
-- without first having to dial or bring up a VPN.
function M.isOnline(flags)
  if type(flags) ~= "number" then return nil end
  local known = hs.network.reachability.flags
  return (flags & known.reachable) ~= 0 and (flags & known.connectionRequired) == 0
end

function M.start()
  if not layer or M.watching then return M end

  -- Kept current by macOS's own watcher, so an open never asks the network.
  local internet = hs.network.reachability.internet()
  M.online = M.isOnline(internet:status())
  M.watching = layer.watch({
    start = function() internet:setCallback(function(_, flags) M.online = M.isOnline(flags) end):start() end,
    stop  = function() internet:stop() end,
  })

  -- Asked once, a turn after start: NSHost may wait on the network to
  -- answer, and the name does not change while the layer runs.
  M.naming = layer.after(0, function()
    M.naming = nil
    local ok, name = pcall(hs.host.localizedName)
    M.hostname = ok and type(name) == "string" and name ~= "" and name or nil
  end)
  return M
end

function M.stop()
  for _, d in ipairs({ M.watching or false, M.naming or false }) do
    if d then d.dispose() end
  end
  M.watching, M.naming, M.online = nil, nil, nil
  return M
end

-- Pasteboard types an app sets when what it copied is not for keeping --
-- a password, a one-time code, text an expander is about to replace --
-- from nspasteboard.org, as TextClipboardHistory honours them.
local PRIVATE_TYPES = {
  "org.nspasteboard.ConcealedType",
  "org.nspasteboard.TransientType",
  "org.nspasteboard.AutoGeneratedType",
  "com.agilebits.onepassword",
  "de.petermaurer.TransientPasteboardType",
  "com.typeit4me.clipping",
  "Pasteboard generator type",
}

function M.extension(cl)
  layer = cl
  -- Checked before the text is read: the context reaches `when` clauses and
  -- templates, so a copied password must never enter it.
  local function clipboardIsPrivate()
    local private = {}
    for _, kind in ipairs(cl.setting("ambient", "privateTypes") or {}) do private[kind] = true end
    for _, list in ipairs({ hs.pasteboard.pasteboardTypes and hs.pasteboard.pasteboardTypes() or {},
                            hs.pasteboard.contentTypes and hs.pasteboard.contentTypes() or {} }) do
      for _, kind in ipairs(list) do
        if private[kind] then return true end
      end
    end
    return false
  end

  return {
    name   = "ambient",
    description = "The app in front, the clipboard, this Mac's name and whether it is online, as context keys",
    before = { "finder" },   -- finder reads frontmostApp.

    -- No items: this contributes facts, not rows.
    menus = {},

    settings = {
      privateTypes = {
        type = "array", default = PRIVATE_TYPES,
        description = "Pasteboard types that keep what was copied out of the context: a password, a one-time code",
      },
    },

    capture = function(ctx)
      local app = hs.application.frontmostApplication()

      -- Name and bundle id both: the name is what you read, the id is
      -- the only identity a running process and Spotlight agree on.
      ctx.frontmostApp   = (app and app:name()) or ""
      ctx.frontmostAppID = app and app:bundleID() or nil

      ctx.clipboard = (not clipboardIsPrivate() and hs.pasteboard.getContents()) or ""

      ctx.hostname = M.hostname
      ctx.online   = M.online
    end,

    -- A clipboard row means that text, not whatever is on the pasteboard
    -- by the time you pick an action, so ${clipboard} follows the row it
    -- was opened from.
    scope = function(subject, scoped)
      if subject.value
         and (subject.kind == "clipboard" or subject.kind == "url") then
        scoped.clipboard = subject.value
      end
    end,
  }
end

-- Checks for this extension, run by test.lua.

return M
